

import java.awt.TextArea;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ashwi
 */
public class CalculatorApp extends javax.swing.JFrame {

    private double re1 = 0, br = 0, time = 1, ttta = 0, tttaa = 0, sqnum = 0;
    private int index = 0, indexb = 0, num = 0, number = 1, brsqrt = 0;
    @SuppressWarnings("FieldMayBeFinal")
     double a[] = new double[50];
    int sa[] = new int[50];
    private double aaaa[] = new double[50];
    private int saaaa[] = new int[50];
    private double ab[] = new double[50];
    private int sab[] = new int[50];
    private long point = -1, points = 1, sqrt = -1;
    private boolean againagain1 = false;
    private boolean againagain2 = false;
    private TextArea TextArea3 = new TextArea();
    private boolean historyIsOpened = false;

    /**
     * Creates new form Calculator
     */
    public CalculatorApp() {
        initComponents();
        jButton1.setBounds(jButton1.getX(), jButton1.getY(), jButton1.getWidth(), jButton1.getHeight());
        jButton1.addKeyListener(new KeyListenerDemo());
        jButton2.addKeyListener(new KeyListenerDemo());
        jButton3.addKeyListener(new KeyListenerDemo());
        jButton4.addKeyListener(new KeyListenerDemo());
        jButton5.addKeyListener(new KeyListenerDemo());
        jButton6.addKeyListener(new KeyListenerDemo());
        jButton7.addKeyListener(new KeyListenerDemo());
        jButton8.addKeyListener(new KeyListenerDemo());
        jButton9.addKeyListener(new KeyListenerDemo());
        jButton10.addKeyListener(new KeyListenerDemo());
        jButton11.addKeyListener(new KeyListenerDemo());
        //jPanel1.addKeyListener(new KeyListenerDemo());
        for (int i = 0; i <= a.length - 1; i++) {
            a[i] = i * -1.1;
            ab[i] = i * -1.1;
            aaaa[i] = i * -1.1;
            sa[i] = i * -1;
            saaaa[i] = i * -1;
            sab[i] = i * -1;
        }
        
        File folder = new File("C:\\CalculatorApp\\message.txt");  // Example path

        if (!folder.exists())
            folder.mkdirs();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonhistory = new javax.swing.JButton();
        myLabelSign = new javax.swing.JLabel();
        myLabelAnswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(500, 50, 500, 500));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(67, 64, 64));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(385, 585));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(385, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(344, 389));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 204));
        jButton1.setText("1");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 204));
        jButton2.setText("2");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 0, 204));
        jButton3.setText("3");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 0, 204));
        jButton4.setText("4");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 0, 204));
        jButton5.setText("5");
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 0, 204));
        jButton6.setText("6");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 0, 204));
        jButton7.setText("7");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 0, 204));
        jButton8.setText("8");
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 0, 204));
        jButton9.setText("9");
        jButton9.setBorderPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 0, 204));
        jButton10.setText("0");
        jButton10.setBorderPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 0, 0));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 0, 204));
        jButton11.setText("00");
        jButton11.setBorderPainted(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 0, 204));
        jButton12.setText(".");
        jButton12.setBorderPainted(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 0, 204));
        jButton13.setText("+");
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 0, 0));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 0, 204));
        jButton14.setText("-");
        jButton14.setBorderPainted(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton15.setForeground(new java.awt.Color(51, 0, 204));
        jButton15.setText("*");
        jButton15.setBorderPainted(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 0, 0));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton16.setForeground(new java.awt.Color(51, 0, 204));
        jButton16.setText("/");
        jButton16.setBorderPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(0, 0, 0));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton17.setForeground(new java.awt.Color(51, 0, 204));
        jButton17.setText("(");
        jButton17.setBorderPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(0, 0, 0));
        jButton18.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton18.setForeground(new java.awt.Color(51, 0, 204));
        jButton18.setText(")");
        jButton18.setBorderPainted(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(0, 0, 0));
        jButton19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(51, 0, 204));
        jButton19.setText("Sqrt");
        jButton19.setBorderPainted(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(0, 0, 0));
        jButton22.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jButton22.setForeground(new java.awt.Color(51, 0, 204));
        jButton22.setText("=");
        jButton22.setBorderPainted(false);
        jButton22.setIconTextGap(1);
        jButton22.setPreferredSize(new java.awt.Dimension(31, 57));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(0, 0, 0));
        jButton20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(51, 0, 204));
        jButton20.setText("Delet");
        jButton20.setBorderPainted(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(0, 0, 0));
        jButton21.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jButton21.setForeground(new java.awt.Color(51, 0, 204));
        jButton21.setText("C");
        jButton21.setBorderPainted(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 346, 386));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 346, 390));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jButtonhistory.setBackground(new java.awt.Color(102, 102, 102));
        jButtonhistory.setForeground(new java.awt.Color(102, 102, 102));
        jButtonhistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thippeswamy/icones/Screenshot (2176)_1.png"))); // NOI18N
        jButtonhistory.setBorderPainted(false);
        jButtonhistory.setFocusCycleRoot(true);
        jButtonhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhistoryActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonhistory);
        jButtonhistory.setBounds(295, 3, 45, 40);

        myLabelSign.setBackground(new java.awt.Color(102, 102, 102));
        myLabelSign.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        myLabelSign.setForeground(new java.awt.Color(255, 255, 255));
        myLabelSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myLabelSign.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        myLabelSign.setOpaque(true);
        jPanel1.add(myLabelSign);
        myLabelSign.setBounds(3, 3, 338, 70);

        myLabelAnswer.setBackground(new java.awt.Color(102, 102, 102));
        myLabelAnswer.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        myLabelAnswer.setForeground(new java.awt.Color(255, 255, 255));
        myLabelAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myLabelAnswer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        myLabelAnswer.setName(""); // NOI18N
        myLabelAnswer.setOpaque(true);
        jPanel1.add(myLabelAnswer);
        myLabelAnswer.setBounds(3, 75, 338, 68);

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 344, 146));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 367, 563));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Jbutton5();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Jbutton5() {
        if (time == 1) {
            re1 = re1 * 10 + 5;
            num = 1;
            number = 11;
            every();
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jbutton1();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Jbutton1() {
        if (time == 1) {
            re1 = re1 * 10 + 1;
            num = 1;
            number = 11;
            every();
        }
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Jbutton7();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Jbutton7() {
        if (time == 1) {
            re1 = re1 * 10 + 7;
            num = 1;
            number = 11;
            every();
        }
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Jbutton8();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void Jbutton8() {
        if (time == 1) {
            re1 = re1 * 10 + 8;
            num = 1;
            number = 11;
            every();
        }
    }

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Jbutton11();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void Jbutton11() {
        if (time == 1) {
            re1 = re1 * 100;
            num = 1;
            number = 11;
            every();
        }
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Jbutton9();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void Jbutton9() {
        if (time == 1) {
            re1 = re1 * 10 + 9;
            num = 1;
            number = 11;
            every();
        }
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Jbutton10();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void Jbutton10() {
        if (time == 1) {
            re1 = re1 * 10;
            num = 1;
            number = 11;
            every();
        }
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Jbutton6();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Jbutton6() {
        if (time == 1) {
            re1 = re1 * 10 + 6;
            num = 1;
            number = 11;
            every();
        }
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        Jbutton13();
        time = 1;
    }//GEN-LAST:event_jButton13ActionPerformed

    private void Jbutton13() {

        if (num == 1) {
            if (sqrt != 1) {
                a[index] = re1 / points;
                sa[index] = 13;
                disp1(1);
                re1 = 0;
                num = 2;
                index++;
            } else {
                sqnum = Math.sqrt((re1 / points));
                a[index] = sqnum;
                sa[index] = 13;
                disp1(1);
                num = 2;
                index++;
                re1 = 0;
            }
            num = 2;
            againagain2 = true;
        } else if (num == 2) {
            sa[index - 1] = 13;
            index--;
            disp1(2);
            index++;
            againagain2 = true;
        }
        points = 1;
        point = -1;
        if (br == 0) {
            sqrt = 0;
        }
    }

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Jbutton14();
        time = 1;
    }//GEN-LAST:event_jButton14ActionPerformed

    private void Jbutton14() {
        if (num == 1) {
            if (sqrt != 1) {
                a[index] = re1 / points;
                sa[index] = 12;
                disp1(1);
                re1 = 0;
                index++;
            } else {
                sqnum = Math.sqrt((re1 / points));
                a[index] = sqnum;
                sa[index] = 12;
                disp1(1);
                index++;
                re1 = 0;
            }
            againagain2 = true;
            num = 2;
        } else if (num == 2) {
            sa[index - 1] = 12;
            index--;
            disp1(2);
            index++;
            againagain2 = true;
        }
        points = 1;
        point = -1;
        if (br == 0) {
            sqrt = 0;
        }
    }

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Jbutton12();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void Jbutton12() {
        if (point == -1 && points == 1 && time == 1) {
            point = 1;
            points = 1;
            disp1(3);
            againagain1 = true;
        }
    }

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Jbutton16();
        time = 1;
    }//GEN-LAST:event_jButton16ActionPerformed

    private void Jbutton16() {
        if (num == 1) {
            if (sqrt != 1) {
                a[index] = re1 / points;
                sa[index] = 15;
                disp1(1);
                re1 = 0;
                num = 2;
                index++;
            } else {
                sqnum = Math.sqrt((re1 / points));
                a[index] = sqnum;
                sa[index] = 15;
                disp1(1);
                num = 2;
                index++;
                re1 = 0;
            }
            againagain2 = true;
            num = 2;
        } else if (num == 2) {
            sa[index - 1] = 15;
            index--;
            disp1(2);
            index++;
            againagain2 = true;
        }
        points = 1;
        point = -1;
        if (br == 0) {
            sqrt = 0;
        }
    }

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        Jbutton17();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void Jbutton17() {
        if (br == 0 && num == 2) {
            if (sqrt == 1) {
                brsqrt = 1;
                sqrt = 0;
            }
            if (sa[index - 1] == 12) {
                sa[index - 1] = 2112;
            }
            if (sa[index - 1] == 13) {
                sa[index - 1] = 2113;
            }
            if (sa[index - 1] == 14) {
                sa[index - 1] = 2114;
            }
            if (sa[index - 1] == 15) {
                sa[index - 1] = 2115;
            }
            br = 1;
            for (int i = 0; i <= sa.length - 1; i++) {
                ab[i] = a[i];
                sab[i] = sa[i];
            }
            tttaa = ttta;
            for (int i = 0; i <= sa.length - 1; i++) {
                a[i] = i * -1.1;
                sa[i] = i * -1;
            }
            indexb = index;
            index = 0;
            re1 = 0;
            myLabelAnswer.setText(Double.toString(tttaa));
            myLabelSign.setText(" ( ");
            myLabelAnswer.setText(Double.toString(tttaa));
            myLabelSign.setText(Double.toString(re1 / points) + myLabelSign.getText());
        }
    }

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        Jbutton18();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void Jbutton18() {
        if (br == 1) {
            double asw = 0;
            if (brsqrt == 1) {
                ttta = Math.sqrt(ttta);
            }
            if (sab[indexb - 1] == 2112) {
                asw = tttaa - ttta;
            }
            if (sab[indexb - 1] == 2113) {
                asw = tttaa + ttta;
            }
            if (sab[indexb - 1] == 2114) {
                asw = tttaa * ttta;
            }
            if (sab[indexb - 1] == 2115) {
                asw = tttaa / ttta;
            }
            myLabelAnswer.setText(Double.toString(asw));
            myLabelSign.setText(")");
            myLabelAnswer.setText(Double.toString(asw));
            index = indexb;
            indexb = 0;
            ab[index] = ttta;
            re1 = 0;
            num = 2;
            br = 0;
            for (int i = 0; i < sa.length; i++) {
                a[i] = ab[i];
                sa[i] = sab[i];
            }

            for (int i = 0; i <= sa.length - 1; i++) {
                ab[i] = i * -1.1;
                sab[i] = i * -1;
            }
            if (sa[index - 1] == 2112) {
                sa[index - 1] = 12;
            }
            if (sa[index - 1] == 2113) {
                sa[index - 1] = 13;
            }
            if (sa[index - 1] == 2114) {
                sa[index - 1] = 14;
            }
            if (sa[index - 1] == 2115) {
                sa[index - 1] = 15;
            }
            index++;
            brsqrt = 0;

            myLabelSign.setText(Double.toString(re1 / points) + myLabelSign.getText());
        }
    }
    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jbutton19();
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jbutton19() {
        point = -1;
        sqrt = 1;
        sqnum = 0;
        points = 1;
    }

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Jbutton22();
    }//GEN-LAST:event_jButton22ActionPerformed
    private void Jbutton22() {
        number = 12;
        num = 2;
        every();
        writing_hiostory();
        index = 0;
        for (int ty = 0; ty < a.length; ty++) {
            a[ty] = ty * -1.1;
            sa[ty] = ty * -1;
        }
        a[0] = re1;
        re1 = 0;
        num = 2;
        index++;
        point = -1;
        points = 1;

        if (a[0] == (int) a[0]) {
            myLabelSign.setText(Integer.toString((int) a[0]) + " ");
        } else {
            myLabelSign.setText(Double.toString(a[0]) + " ");
        }
        time = 2;
    }
    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Jbutton15();
        time = 1;
    }//GEN-LAST:event_jButton15ActionPerformed

    private void Jbutton15() {
        if (num == 1) {
            if (sqrt != 1 && br == 0) {
                a[index] = re1 / points;
                sa[index] = 14;
                disp1(1);
                re1 = 0;
                num = 2;
                index++;
            } else {
                sqnum = Math.sqrt((re1 / points));
                a[index] = sqnum;
                sa[index] = 14;
                disp1(1);
                num = 2;
                index++;
                re1 = 0;
            }
            againagain2 = true;
            num = 2;
        } else if (num == 2) {
            sa[index - 1] = 14;
            index--;
            disp1(2);
            index++;
            againagain2 = true;
        }
        points = 1;
        point = -1;
        if (br == 0) {
            sqrt = 0;
        }
    }

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        Jbutton20();
    }//GEN-LAST:event_jButton20ActionPerformed
    private void Jbutton20() {
        long yui = (long) re1;
        if (yui != 0) {
            yui = yui / 10;
            re1 = yui;
        } else if (index >= 1) {
            a[index] = index * -1.1;
            sa[index] = index * -1;
            index--;
            re1 = a[index];
        }
        if (points >= 10) {
            points = points / 10;
        }
        number = 1;
        every();
    }
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Jbutton21();
    }//GEN-LAST:event_jButton21ActionPerformed
    private void Jbutton21() {
        myLabelSign.setText("");
        myLabelAnswer.setText("0");
        re1 = 0;
        index = 0;
        sqrt = 0;
        points = 1;
        point = -1;
        br = 0;
        time = 1;
        num = 0;
        for (int ty = 0; ty < a.length; ty++) {
            a[ty] = ty * -1.1;
            sa[ty] = ty * -1;
            aaaa[ty] = ty * -1.1;
            saaaa[ty] = ty * -1;
        }
        myLabelSign.setText("");
    }
        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Jbutton2();
        }//GEN-LAST:event_jButton2ActionPerformed

    private void Jbutton2() {
        if (time == 1) {
            re1 = re1 * 10 + 2;
            num = 1;
            number = 11;
            every();
        }

    }

        private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            Jbutton3();
        }//GEN-LAST:event_jButton3ActionPerformed

    private void Jbutton3() {
        if (time == 1) {
            re1 = re1 * 10 + 3;
            num = 1;
            number = 11;
            every();
        }
    }

        private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            Jbutton4();
        }//GEN-LAST:event_jButton4ActionPerformed

    private void Jbutton4() {
        if (time == 1) {
            re1 = re1 * 10 + 4;
            num = 1;
            number = 11;
            every();
        }

    }

    private void jButtonhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhistoryActionPerformed
        if (!historyIsOpened) {
            historyIsOpened = true;
            TextArea3.setSize(jPanel2.getWidth(), jPanel2.getHeight());
            TextArea3.locate(jPanel2.getX(), jPanel2.getY());
            TextArea3.setBackground(new java.awt.Color(102, 102, 102));
            TextArea3.setForeground(new java.awt.Color(255, 255, 255));
            jPanel2.setSize(0, 0);
            String ss = null;
            StringBuffer mer = new StringBuffer();
            {

                try {
                    BufferedReader br = null;
                    FileReader fr = null;
                    fr = new FileReader("C:\\CalculatorApp\\message.txt");
                    br = new BufferedReader(fr);
                    String sCurrentLine = "";
                    while ((sCurrentLine = br.readLine()) != null) {
                        ss = sCurrentLine;
                        mer.append(ss).append("\n");//mer.append(ss+"\n");
                        //TextArea3.setText(ss + TextArea3.getText());
                    }
                } catch (IOException e) {
                }
            }
            TextArea3.setText(mer.toString());
            TextArea3.setFont(new java.awt.Font("Tahoma", 0, 18));
            try {
                jPanel3.add(TextArea3);
            } catch (Exception e) {
            }
            jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_jButtonhistoryActionPerformed

    private void writing_hiostory() {
        String ss = null;
        StringBuffer mer = new StringBuffer();
        {

            try {
                BufferedReader br = null;
                FileReader fr = null;
                fr = new FileReader("C:\\CalculatorApp\\message.txt");
                br = new BufferedReader(fr);
                String sCurrentLine = "";
                while ((sCurrentLine = br.readLine()) != null) {
                    ss = sCurrentLine;
                    mer.append(ss).append("\n");//mer.append(ss+"\n");
                    //TextArea3.setText(ss + TextArea3.getText());
                }
            } catch (IOException e) {
            }
        }
        PrintWriter writer;
        try {
            writer = new PrintWriter("C:\\CalculatorApp\\message.txt", "UTF-8");
            writer.println((mer.toString() + myLabelSign.getText() + " = " + myLabelAnswer.getText()));
            writer.close();
        } catch (FileNotFoundException | UnsupportedEncodingException e) {
        }
    }

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        jButton1.addKeyListener(new KeyListenerDemo());
        jButton2.addKeyListener(new KeyListenerDemo());
        jButton3.addKeyListener(new KeyListenerDemo());
        jButton4.addKeyListener(new KeyListenerDemo());
        jButton5.addKeyListener(new KeyListenerDemo());
        jButton6.addKeyListener(new KeyListenerDemo());
        jButton7.addKeyListener(new KeyListenerDemo());
        jButton8.addKeyListener(new KeyListenerDemo());
        jButton9.addKeyListener(new KeyListenerDemo());
        jButton10.addKeyListener(new KeyListenerDemo());
        jButton11.addKeyListener(new KeyListenerDemo());
        //KeyListenerDemo
    }//GEN-LAST:event_formKeyTyped

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if (historyIsOpened) {
            jPanel2.setSize(jPanel3.getWidth(), jPanel3.getHeight());
            jPanel2.locate(jPanel3.getX(), jPanel3.getY());
            jPanel2.setVisible(true);
            TextArea3.setSize(0, 0);
            historyIsOpened = false;
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
        // TODO add your handling code here:
        /*
        switch (evt.getKeyChar()) {
                case '1' ->
                    Jbutton1();
                default -> {
                    
                }
        }
        */
    }//GEN-LAST:event_jButton1KeyTyped

    private void disp() {
        int i12 = 0;
        myLabelSign.setText("");
        String s123 = "";
        String s12 = "";
        for (i12 = 0; i12 * -1.1 != a[i12] && i12 * -1 != sa[i12]; i12++) {
            if (a[i12] == (int) a[i12]) {
                int ttteb1 = (int) a[i12];
                s123 = s123 + s12 + Integer.toString(ttteb1);
            } else {
                s123 = s123 + s12 + Double.toString(a[i12]);
            }

            s12 = myLabelSign.getText();
            if (sa[i12] == 12) {
                s123 = s123 + s12 + "-";
            }
            if (sa[i12] == 13) {
                s123 = s123 + s12 + "+";
            }
            if (sa[i12] == 14) {
                s123 = s123 + s12 + "*";
            }
            if (sa[i12] == 15) {
                s123 = s123 + s12 + "/";
            }
        }
        myLabelSign.setText("");
        s12 = myLabelSign.getText();
        if (a[i12] != i12 * -1.1) {
            if (a[i12] == (int) a[i12]) {
                int ttteb1 = (int) a[i12];
                s123 = s123 + s12 + Integer.toString(ttteb1);
            } else {
                s123 = s123 + s12 + Double.toString(a[i12]);
            }
        }
        myLabelSign.setText(s123);
    }

    @SuppressWarnings("SuspiciousIndentAfterControlStatement")
    public void disp1(int q) {
        if (againagain1) {
            String s12 = myLabelSign.getText();
            s12 = s12.substring(0, s12.length());
        }
        if (q == 1) {
            String s12 = myLabelSign.getText();
            int i12 = index;
            if (sa[i12] == 12) {
                myLabelSign.setText(s12 + "-");
            }
            if (sa[i12] == 13) {
                myLabelSign.setText(s12 + "+");
            }
            if (sa[i12] == 14) {
                myLabelSign.setText(s12 + "*");
            }
            if (sa[i12] == 15) {
                myLabelSign.setText(s12 + "/");
            }
        } else if (q == 2) {
            String s12 = myLabelSign.getText();
            if (s12.length() >= 1) {
                s12 = s12.substring(0, s12.length() - 1);
            }
            int i12 = index;
            if (sa[i12] == 12) {
                myLabelSign.setText(s12 + "-");
            }
            if (sa[i12] == 13) {
                myLabelSign.setText(s12 + "+");
            }
            if (sa[i12] == 14) {
                myLabelSign.setText(s12 + "*");
            }
            if (sa[i12] == 15) {
                myLabelSign.setText(s12 + "/");
            }
        } else if (q == 3 && againagain2) {
            String s12 = myLabelSign.getText();
            myLabelSign.setText(s12 + "0.");
            againagain1 = true;
        } else if (q == 3 && !againagain2) {

        }

    }

    protected void every() {
        againagain1 = false;
        if (number == 11) {
            if (point >= 1) {
                points = points * 10;
            }
        }
        if (sqrt != 1) {
            a[index] = re1 / points;
        } else {
            sqnum = Math.sqrt((re1 / points));
            a[index] = sqnum;
        }

        disp();

        for (int y1 = 0; y1 < sa.length; y1++) {
            aaaa[y1] = a[y1];
            saaaa[y1] = sa[y1];
        }

        for (int ii = 1; (a[ii] != ii * -1.1 || a[ii - 1] != (ii - 1) * -1.1) && (ii <= a.length - 1); ii++) {
            if (sa[ii - 1] == 14) {
                a[ii] = a[ii - 1] * a[ii];
                a[ii - 1] = 0;
                if (ii >= 2) {
                    sa[ii - 1] = sa[ii - 2];
                } else {
                    sa[ii - 1] = 13;
                }
            }

            if (sa[ii - 1] == 15) {
                a[ii] = a[ii - 1] / a[ii];
                if (ii >= 2) {
                    sa[ii - 1] = sa[ii - 2];
                } else {
                    sa[ii - 1] = 13;
                }
                a[ii - 1] = 0;
            }
        }

        double ttt = a[0];
        for (int i = 1; (a[i] != i * -1.1) && (i <= a.length - 1); i++) {
            if (sa[i - 1] == 1) {
                ttt = ttt + a[i];
            }
            if (sa[i - 1] == 12) {
                ttt = ttt - a[i];
            }
            if (sa[i - 1] == 13) {
                ttt = ttt + a[i];
            }
        }
        ttta = ttt;
        if (brsqrt == 1) {
            ttt = Math.sqrt(ttt);
        }
        double ttteb = 0;
        if (br == 1) {
            if (sab[indexb - 1] == 2112) {
                ttteb = tttaa - ttt;
            }
            if (sab[indexb - 1] == 2113) {
                ttteb = tttaa + ttt;
            }
            if (sab[indexb - 1] == 2114) {
                ttteb = tttaa * ttt;
            }
            if (sab[indexb] == 2115) {
                ttteb = tttaa / ttt;
            }
        }
        if (br == 0) {
            ttteb = ttta;
        }
        if (ttteb == (int) ttteb) {
            int ttteb1 = (int) ttteb;
            myLabelAnswer.setText(Integer.toString(ttteb1));
        } else {
            myLabelAnswer.setText(Double.toString(ttteb));
        }
        if (number == 12) {
            re1 = ttteb;
            ttt = 0;
        }
        for (int y1 = 0; y1 < sa.length; y1++) {
            a[y1] = aaaa[y1];
            sa[y1] = saaaa[y1];
        }
        number = 1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculatorApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonhistory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel myLabelAnswer;
    private javax.swing.JLabel myLabelSign;
    // End of variables declaration//GEN-END:variables

    class KeyListenerDemo implements KeyListener {

        @Override
        public void keyPressed(KeyEvent e) {
            //System.out.println("Key code : " + e.getKeyCode());
        }

        @Override
        public void keyReleased(KeyEvent e) {
            // System.out.println("Key code : " + e.getKeyCode());
        }

        @Override
        public void keyTyped(KeyEvent e) {

            switch (e.getKeyChar()) {
                case '1' ->
                    Jbutton1();
                case '2' ->
                    Jbutton2();
                case '3' ->
                    Jbutton3();
                case '4' ->
                    Jbutton4();
                case '5' ->
                    Jbutton5();
                case '6' ->
                    Jbutton6();
                case '7' ->
                    Jbutton7();
                case '8' ->
                    Jbutton8();
                case '9' ->
                    Jbutton9();
                case '0' ->
                    Jbutton10();
                case '.' ->
                    Jbutton12();
                case '+' ->
                    Jbutton13();
                case '-' ->
                    Jbutton14();
                case '*' ->
                    Jbutton15();
                case '/' ->
                    Jbutton16();
                case '(' ->
                    Jbutton17();
                case ')' ->
                    Jbutton18();
                case KeyEvent.VK_BACK_SPACE ->
                    Jbutton20();
                case 'c','C' ->
                    Jbutton21();
                case KeyEvent.VK_ENTER ->
                    Jbutton22();
                default -> {
                }
            }

        }
    }
}
